#:schema https://api.nuon.co/v1/general/config-schema?type=helm

name         = "application_load_balancer"
type         = "helm_chart"
chart_name   = "application-load-balancer"
dependencies = ["candy_app", "certificate"]
namespace    = "spookycandy"

[public_repo]
repo      = "https://github.com/matt-zach-s/spookycandy-nuon"
directory = "your-app/src/components/alb"
branch    = "main"

[values]
domain_certificate = "{{.nuon.components.certificate.outputs.public_domain_certificate_arn}}"
domain             = "{{.nuon.inputs.inputs.sub_domain}}.{{.nuon.install.sandbox.outputs.nuon_dns.public_domain.name}}"
https_port         = "443"
service_name       = "spooky-candy-app"
service_port       = "80"
install_name       = "{{.nuon.install.id}}"
namespace          = "spookycandy"
healthcheck_path   = "/"
